### ISSUE TITLE
Documentation is missing

### ISSUE THREAD

**Issue by abeger** [NARKOZ/gitlab#612] opened 2021-03-30 15:32 UTC
https://www.rubydoc.info/gems/gitlab/frames is returning a 404. Tried with [other](https://www.rubydoc.info/gems/gitlab/4.16.1) [versions](https://www.rubydoc.info/gems/gitlab/4.14.1), too, and got the same problem.

**Comment by wiebersk** [comment] 2021-04-06 18:46
I noticed this too and found it at https://rubydoc.info/github/NARKOZ/gitlab which works for me now. I'm unsure why the normal gem doc URL isn't working.

**Comment by NARKOZ** [comment] 2021-04-07 11:28
Duplicate of #589

**Closed by NARKOZ** 2021-04-07 11:28 UTC
