### ISSUE TITLE
wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by aep** [NARKOZ/gitlab#388] opened 2018-06-04 06:03 UTC
any error from gitlab will result in "wrong number of arguments (given 2, expected 1)" 

```
Gitlab.projects(per_page: 5)
```

```
gitlab (4.4.0) lib/gitlab/objectified_hash.rb:26:in `method_missing'
gitlab (4.4.0) lib/gitlab/error.rb:40:in `build_error_message'
gitlab (4.4.0) lib/gitlab/error.rb:16:in `initialize'
gitlab (4.4.0) lib/gitlab/request.rb:69:in `exception'
gitlab (4.4.0) lib/gitlab/request.rb:69:in `raise'
gitlab (4.4.0) lib/gitlab/request.rb:69:in `validate'
gitlab (4.4.0) lib/gitlab/request.rb:44:in `block (2 levels) in <class:Request>'
gitlab (4.4.0) lib/gitlab/client/projects.rb:19:in `projects'
app/controllers/gitlab_controller.rb:7:in `home'
```

**Comment by bonkey** [comment] 2018-06-05 13:47
Seems like #377

**Comment by asedge** [comment] 2018-06-08 14:22
I'm going to close this as a duplicate of #359 as I think they're all related.  Looking for people to try out a branch I pushed up.

**Closed by asedge** 2018-06-08 14:22 UTC
Labels: bug
