### ISSUE TITLE
Documentation links are broken

### ISSUE THREAD

**Issue by cortesoft** [NARKOZ/gitlab#590] opened 2020-11-16 20:20 UTC
The links at the top of the readme to the documentation return 404s: https://www.rubydoc.info/gems/gitlab/frames

**Comment by hoijui** [comment] 2020-11-22 09:17
duplicate of https://github.com/NARKOZ/gitlab/issues/590

**Comment by NARKOZ** [comment] 2020-11-28 08:52
Works for me. Could you check again, please?

**Comment by hoijui** [comment] 2020-11-28 09:03
ahh yep, works again now! :-)

**Comment by NARKOZ** [comment] 2020-11-28 09:30
Great 🥳

**Closed by NARKOZ** 2020-11-28 09:30 UTC
